import pandas as pd
# List of tuples
data = [
('Yield', 'Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw'),
('Production', 'Beeswax'),
('Yield', 'Other oil seeds, n.e.c.'),
('Yield', 'Sesame seed'),
('Area harvested', 'Cassava, fresh'),
('Yield', 'Seed cotton, unginned'),
('Yield', 'Cocoa beans'),
('Area harvested', 'Peas, green'),
('Production', 'Pineapples'),
('Yield', 'Barley'),
('Production', 'Cashew nuts, in shell'),
('Yield', 'Watermelons'),
('Yield', 'Kenaf, and other textile bast fibres, raw or retted'),
('Area harvested', 'Chillies and peppers, dry (Capsicum spp., Pimenta spp.),, raw'),
('Yield', 'Figs'),
('Production', 'Jute, raw or retted'),
('Production', 'Raw milk of buffalo'),
('Area harvested', 'Sorghum'),
('Producing Animals/Slaughtered', 'Raw hides and skins of cattle'),
('Production', 'Raw milk of goats'),
('Production', 'Raw hides and skins of cattle'),
('Yield', 'Pumpkins, squash and gourds'),
('Production', 'Ghee from buffalo milk'),
('Production', 'Cauliflowers and broccoli'),
('Production', 'Sugar cane'),
('Area harvested', 'Tea leaves'),
('Stocks', 'Buffalo'),
('Production', 'Cherries'),
('Production', 'Wheat'),
('Area harvested', 'Coffee, green'),
('Area harvested', 'Nutmeg, mace, cardamoms, raw'),
('Production', 'Peas, dry'),
('Yield', 'Other fruits, n.e.c.'),
('Production', 'Cucumbers and gherkins'),
('Production', 'Bananas'),
('Yield', 'Pepper (Piper spp.),, raw'),
('Area harvested', 'Other tropical fruits, n.e.c.'),
('Yield', 'Raw hides and skins of goats or kids'),
('Producing Animals/Slaughtered', 'Fat of pigs'),
('Area harvested', 'Oranges'),
('Production', 'Butter of buffalo milk'),
('Production', 'Fat of pigs'),
('Area harvested', 'Potatoes'),
('Production', 'Peas, green'),
('Yield', 'Green garlic'),
('Yield', 'Sunflower seed'),
('Yield', 'Natural rubber in primary forms'),
('Yield', 'Rice'),
('Yield', 'Cantaloupes and other melons'),
('Yield', 'Peaches and nectarines'),
('Production', 'Oil of sesame seed'),
('Producing Animals/Slaughtered', 'Edible offal of sheep, fresh, chilled or frozen'),
('Area harvested', 'Mangoes, guavas and mangosteens'),
('Yield', 'Groundnuts, excluding shelled'),
('Production', 'Edible offal of sheep, fresh, chilled or frozen'),
('Production', 'Raw cane or beet sugar (centrifugal only),'),
('Production', 'Natural honey'),
('Area harvested', 'Safflower seed'),
('Production', 'Cabbages'),
('Area harvested', 'Ginger, raw'),
('Area harvested', 'Other stimulant, spice and aromatic crops, n.e.c.'),
('Production', 'Cotton lint, ginned'),
('Producing Animals/Slaughtered', 'Cattle fat, unrendered'),
('Area harvested', 'Tangerines, mandarins, clementines'),
('Yield', 'Pineapples'),
('Production', 'Raw silk (not thrown),'),
('Production', 'Nutmeg, mace, cardamoms, raw'),
('Production', 'Cattle fat, unrendered'),
('Yield', 'Cashew nuts, in shell'),
('Stocks', 'Swine / pigs'),
('Yield/Carcass Weight', 'Meat of goat, fresh or chilled'),
('Yield', 'Raw milk of buffalo'),
('Yield', 'Raw milk of goats'),
('Production', 'Potatoes'),
('Yield', 'Raw hides and skins of cattle'),
('Area harvested', 'Sweet potatoes'),
('Yield', 'Cauliflowers and broccoli'),
('Yield', 'Sugar cane'),
('Production', 'Linseed'),
('Yield', 'Cherries'),
('Yield', 'Wheat'),
('Area harvested', 'Chillies and peppers, green (Capsicum spp. and Pimenta spp.),'),
('Production', 'Other pulses n.e.c.'),
('Stocks', 'Goats'),
('Yield', 'Peas, dry'),
('Yield', 'Cucumbers and gherkins'),
('Stocks', 'Camels'),
('Production', 'Lettuce and chicory'),
('Yield', 'Bananas'),
('Stocks', 'Sheep'),
('Area harvested', 'Tomatoes'),
('Production', 'Coconuts, in shell'),
('Production', 'Hen eggs in shell, fresh'),
('Production', 'Apples'),
('Stocks', 'Ducks'),
('Yield', 'Peas, green'),
('Production', 'Tangerines, mandarins, clementines'),
('Production', 'Cotton seed'),
('Area harvested', 'Castor oil seeds'),
('Production', 'Papayas'),
('Production', 'Sweet potatoes'),
('Yield', 'Cabbages'),
('Yield', 'Nutmeg, mace, cardamoms, raw'),
('Production', 'Edible offal of buffalo, fresh, chilled or frozen'),
('Milk Animals', 'Raw milk of camel'),
('Producing Animals/Slaughtered', 'Sheep fat, unrendered'),
('Production', 'Cheese from whole cow milk'),
('Area harvested', 'Areca nuts'),
('Production', 'Apricots'),
('Yield', 'Potatoes'),
('Area harvested', 'Millet'),
('Area harvested', 'Walnuts, in shell'),
('Production', 'Onions and shallots, dry (excluding dehydrated),'),
('Yield', 'Linseed'),
('Production', 'Raw milk of cattle'),
('Yield', 'Other pulses n.e.c.'),
('Production', 'Rape or colza seed'),
('Stocks', 'Cattle'),
('Yield', 'Lettuce and chicory'),
('Area harvested', 'Other citrus fruit, n.e.c.'),
('Production', 'Other meat of mammals, fresh or chilled'),
('Area harvested', 'Other berries and fruits of the genus vaccinium n.e.c.'),
('Yield', 'Coconuts, in shell'),
('Production', 'Coconut oil'),
('Yield', 'Hen eggs in shell, fresh'),
('Area harvested', 'Eggplants (aubergines),'),
('Yield', 'Apples'),
('Production', 'Grapes'),
('Stocks', 'Asses'),
('Yield', 'Tangerines, mandarins, clementines'),
('Producing Animals/Slaughtered', 'Meat of cattle with the bone, fresh or chilled'),
('Laying', 'Hen eggs in shell, fresh'),
('Production', 'Meat of cattle with the bone, fresh or chilled'),
('Area harvested', 'Chick peas, dry'),
('Producing Animals/Slaughtered', 'Meat of chickens, fresh or chilled'),
('Area harvested', 'Carrots and turnips'),
('Production', 'Meat of chickens, fresh or chilled'),
('Production', 'Beans, dry'),
('Area harvested', 'Soya beans'),
('Area harvested', 'Okra'),
('Yield', 'Papayas'),
('Producing Animals/Slaughtered', 'Meat of ducks, fresh or chilled'),
('Producing Animals/Slaughtered', 'Edible offal of goat, fresh, chilled or frozen'),
('Area harvested', 'Other vegetables, fresh n.e.c.'),
('Production', 'Cassava, fresh'),
('Production', 'Edible offal of goat, fresh, chilled or frozen'),
('Yield', 'Other beans, green'),
('Producing Animals/Slaughtered', 'Edible offal of pigs, fresh, chilled or frozen'),
('Production', 'Edible offal of pigs, fresh, chilled or frozen'),
('Area harvested', 'Unmanufactured tobacco'),
('Production', 'Chillies and peppers, dry (Capsicum spp., Pimenta spp.),, raw'),
('Production', 'Shorn wool, greasy, including fleece-washed shorn wool'),
('Yield/Carcass Weight', 'Meat of chickens, fresh or chilled'),
('Yield', 'Apricots'),
('Production', 'Cottonseed oil'),
('Area harvested', 'Pigeon peas, dry'),
('Production', 'Sorghum'),
('Production', 'Whey, dry'),
('Production', 'Eggplants (aubergines),'),
('Area harvested', 'Pears'),
('Area harvested', 'Plums and sloes'),
('Stocks', 'Bees'),
('Area harvested', 'Lemons and limes'),
('Production', 'Pig fat, rendered'),
('Area harvested', 'Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw'),
('Yield', 'Onions and shallots, dry (excluding dehydrated),'),
('Yield', 'Raw milk of cattle'),
('Production', 'Tea leaves'),
('Production', 'Coffee, green'),
('Yield', 'Rape or colza seed'),
('Area harvested', 'Sesame seed'),
('Area harvested', 'Seed cotton, unginned'),
('Production', 'Other tropical fruits, n.e.c.'),
('Yield', 'Jute, raw or retted'),
('Production', 'Oranges'),
('Stocks', 'Chickens'),
('Area harvested', 'Watermelons'),
('Area harvested', 'Kenaf, and other textile bast fibres, raw or retted'),
('Stocks', 'Mules and hinnies'),
('Yield', 'Grapes'),
('Area harvested', 'Other stone fruits'),
('Area harvested', 'Figs'),
('Producing Animals/Slaughtered', 'Meat of sheep, fresh or chilled'),
('Production', 'Meat of sheep, fresh or chilled'),
('Production', 'Whole milk powder'),
('Area harvested', 'Pumpkins, squash and gourds'),
('Production', 'Mangoes, guavas and mangosteens'),
('Production', 'Cream, fresh'),
('Yield', 'Beans, dry'),
('Area harvested', 'Other fruits, n.e.c.'),
('Yield', 'Cassava, fresh'),
('Production', 'Safflower seed'),
('Producing Animals/Slaughtered', 'Raw hides and skins of buffaloes'),
('Area harvested', 'Pepper (Piper spp.),, raw'),
('Production', 'Ginger, raw'),
('Producing Animals/Slaughtered', 'Meat of buffalo, fresh or chilled'),
('Production', 'Other stimulant, spice and aromatic crops, n.e.c.'),
('Production', 'Raw hides and skins of buffaloes'),
('Yield/Carcass Weight', 'Meat of sheep, fresh or chilled'),
('Production', 'Sesame seed'),
('Yield', 'Chillies and peppers, dry (Capsicum spp., Pimenta spp.),, raw'),
('Area harvested', 'Sunflower seed'),
('Area harvested', 'Pomelos and grapefruits'),
('Area harvested', 'Natural rubber in primary forms'),
('Yield', 'Sorghum'),
('Producing Animals/Slaughtered', 'Meat of pig with the bone, fresh or chilled'),
('Area harvested', 'Rice'),
('Yield', 'Eggplants (aubergines),'),
('Production', 'Other stone fruits'),
('Production', 'Figs'),
('Area harvested', 'Groundnuts, excluding shelled'),
('Yield', 'Tea leaves'),
('Production', 'Chillies and peppers, green (Capsicum spp. and Pimenta spp.),'),
('Area harvested', 'Maize (corn),'),
('Yield', 'Coffee, green'),
('Production', 'Tomatoes'),
('Yield', 'Other tropical fruits, n.e.c.'),
('Milk Animals', 'Raw milk of buffalo'),
('Producing Animals/Slaughtered', 'Buffalo fat, unrendered'),
('Area harvested', 'Pineapples'),
('Production', 'Sheep fat, unrendered'),
('Milk Animals', 'Raw milk of goats'),
('Production', 'Buffalo fat, unrendered'),
('Area harvested', 'Cashew nuts, in shell'),
('Yield', 'Oranges'),
('Producing Animals/Slaughtered', 'Raw hides and skins of goats or kids'),
('Production', 'Coir, raw'),
('Production', 'Sunflower seed'),
('Yield', 'Mangoes, guavas and mangosteens'),
('Area harvested', 'Cauliflowers and broccoli'),
('Production', 'Pomelos and grapefruits'),
('Production', 'Margarine and shortening'),
('Production', 'Castor oil seeds'),
('Area harvested', 'Sugar cane'),
('Area harvested', 'Wheat'),
('Yield', 'Safflower seed'),
('Area harvested', 'Cucumbers and gherkins'),
('Area harvested', 'Bananas'),
('Area harvested', 'Lentils, dry'),
('Yield', 'Ginger, raw'),
('Yield', 'Raw hides and skins of buffaloes'),
('Yield', 'Other stimulant, spice and aromatic crops, n.e.c.'),
('Production', 'Maize (corn),'),
('Production', 'Soya bean oil'),
('Production', 'Beer of barley, malted'),
('Production', 'Oil of linseed'),
('Production', 'Areca nuts'),
('Yield', 'Other stone fruits'),
('Yield', 'Sweet potatoes'),
('Production', 'Meat of ducks, fresh or chilled'),
('Production', 'Millet'),
('Stocks', 'Horses'),
('Production', 'Walnuts, in shell'),
('Production', 'Raw milk of camel'),
('Production', 'Ghee from cow milk'),
('Yield', 'Chillies and peppers, green (Capsicum spp. and Pimenta spp.),'),
('Yield/Carcass Weight', 'Meat of cattle with the bone, fresh or chilled'),
('Production', 'Tallow'),
('Area harvested', 'Cabbages'),
('Production', 'Other citrus fruit, n.e.c.'),
('Yield', 'Tomatoes'),
('Production', 'Other berries and fruits of the genus vaccinium n.e.c.'),
('Production', 'Lentils, dry'),
('Yield/Carcass Weight', 'Meat of ducks, fresh or chilled'),
('Producing Animals/Slaughtered', 'Raw hides and skins of sheep or lambs'),
('Production', 'Raw hides and skins of sheep or lambs'),
('Production', 'Molasses'),
('Production', 'Chick peas, dry'),
('Production', 'Carrots and turnips'),
('Yield', 'Pomelos and grapefruits'),
('Area harvested', 'Other oil seeds, n.e.c.'),
('Production', 'Soya beans'),
('Yield', 'Castor oil seeds'),
('Area harvested', 'Linseed'),
('Area harvested', 'Cocoa beans'),
('Production', 'Okra'),
('Area harvested', 'Other pulses n.e.c.'),
('Production', 'Other vegetables, fresh n.e.c.'),
('Producing Animals/Slaughtered', 'Meat of goat, fresh or chilled'),
('Area harvested', 'Barley'),
('Area harvested', 'Lettuce and chicory'),
('Production', 'Meat of goat, fresh or chilled'),
('Yield', 'Maize (corn),'),
('Area harvested', 'Coconuts, in shell'),
('Production', 'Unmanufactured tobacco'),
('Area harvested', 'Apples'),
('Yield', 'Areca nuts'),
('Production', 'Pigeon peas, dry'),
('Producing Animals/Slaughtered', 'Goat fat, unrendered'),
('Production', 'Pears'),
('Yield', 'Millet'),
('Production', 'Plums and sloes'),
('Yield', 'Walnuts, in shell'),
('Yield', 'Raw milk of camel'),
('Production', 'Goat fat, unrendered'),
('Production', 'Lemons and limes'),
('Production', 'Anise, badian, coriander, cumin, caraway, fennel and juniper berries, raw'),
('Area harvested', 'Papayas'),
('Production', 'Meat of buffalo, fresh or chilled'),
('Production', 'Groundnut oil'),
('Production', 'Other oil seeds, n.e.c.'),
('Production', 'Seed cotton, unginned'),
('Production', 'Cocoa beans'),
('Area harvested', 'Other beans, green'),
('Yield', 'Other citrus fruit, n.e.c.'),
('Area harvested', 'Green garlic'),
('Yield', 'Other berries and fruits of the genus vaccinium n.e.c.'),
('Production', 'Barley'),
('Area harvested', 'Cantaloupes and other melons'),
('Yield', 'Lentils, dry'),
('Production', 'Watermelons'),
('Production', 'Kenaf, and other textile bast fibres, raw or retted'),
('Production', 'Meat of pig with the bone, fresh or chilled'),
('Area harvested', 'Peaches and nectarines'),
('Producing Animals/Slaughtered', 'Edible offal of cattle, fresh, chilled or frozen'),
('Area harvested', 'Apricots'),
('Yield', 'Raw hides and skins of sheep or lambs'),
('Milk Animals', 'Raw milk of cattle'),
('Production', 'Edible offal of cattle, fresh, chilled or frozen'),
('Production', 'Silk-worm cocoons suitable for reeling'),
('Yield', 'Chick peas, dry'),
('Yield/Carcass Weight', 'Meat of buffalo, fresh or chilled'),
('Production', 'Pumpkins, squash and gourds'),
('Yield', 'Carrots and turnips'),
('Yield', 'Soya beans'),
('Area harvested', 'Onions and shallots, dry (excluding dehydrated),'),
('Yield', 'Okra'),
('Area harvested', 'Rape or colza seed'),
('Yield', 'Other vegetables, fresh n.e.c.'),
('Production', 'Sunflower-seed oil, crude'),
('Production', 'Other fruits, n.e.c.'),
('Yield/Carcass Weight', 'Meat of pig with the bone, fresh or chilled'),
('Production', 'Pepper (Piper spp.),, raw'),
('Production', 'Rapeseed or canola oil, crude'),
('Area harvested', 'Jute, raw or retted'),
('Production', 'Raw hides and skins of goats or kids'),
('Yield', 'Unmanufactured tobacco'),
('Production', 'Other beans, green'),
('Area harvested', 'Grapes'),
('Production', 'Green garlic'),
('Production', 'Green tea (not fermented),, black tea (fermented), and partly fermented tea, in immediate packings of a content not exceeding 3 kg'),
('Production', 'Oil of maize'),
('Production', 'Natural rubber in primary forms'),
('Producing Animals/Slaughtered', 'Edible offal of buffalo, fresh, chilled or frozen'),
('Yield', 'Pigeon peas, dry'),
('Production', 'Rice'),
('Production', 'Cantaloupes and other melons'),
('Area harvested', 'Cherries'),
('Production', 'Peaches and nectarines'),
('Yield', 'Pears'),
('Production', 'Mushrooms and truffles'),
('Yield', 'Plums and sloes'),
('Area harvested', 'Peas, dry'),
('Yield', 'Lemons and limes'),
('Area harvested', 'Beans, dry'),
('Production', 'Groundnuts, excluding shelled'),
('Production', 'Safflower-seed oil, crude')
]

# Create a DataFrame with columns 'Element' and 'Item'
df = pd.DataFrame(data, columns=['Element', 'Item'])

# Get unique elements
unique_elements = df['Element'].unique()

# Function to filter items related to a specific element
def filter_items_by_element(element):
    return df[df['Element'] == element]['Item'].tolist()

# # Example: Filter items related to 'Production'
# production_items = filter_items_by_element('Production')

# # Output unique elements and filtered production items
# print("Unique Elements:", unique_elements)
# print("Items related to 'Production':", production_items)

